src/profiles/urls.py
from django.urls import path
from .views import my_profile_view


app_name = 'profiles'

urlpatterns = [
    path('', my_profile_view, name='my')
]

src/reports/urls.py
from django.urls import path
from .views import (
    

    create_report_view,
    ReportListView,
    ReportDetailView,
    render_pdf_view,
    UploadTemplateView,
    csv_upload_view
    
    )


app_name = 'reports'

urlpatterns = [
    path('',ReportListView.as_view(),name='main'),
    path('save/',create_report_view,name='create-report'),
    path('upload/',csv_upload_view,name='upload'),
     path('form_file/',UploadTemplateView.as_view(),name='form-file'),
    path('<pk>/',ReportDetailView.as_view(),name = 'detail'),
     path('<pk>/pdf/', render_pdf_view,name='pdf'),
] 

src/reports_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('sales.urls',namespace='sales')),
    path('reports/',include('reports.urls',namespace='reports')),
    path('my_profile/',include('profiles.urls',namespace='profiles')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sales/urls.py
from django.urls import path
#from sales.models import Sale
from .views import (
    
    home_view,    
    SaleListView,
    SaleDetailView,
    
    )


app_name = 'sales'

urlpatterns = [
    path('',home_view,name='home'),
    path('sales/',SaleListView.as_view(),name='list'),
    path('sales/<pk>/',SaleDetailView.as_view(),name='detail')
    #path('sales/<int:pk>/', SaleDetailView.as_view(), name='detail'),
   
    


]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% comment %}Required meta tags{% endcomment %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% comment %}favicon{% endcomment %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />
    {% comment %}Bootstrap CSS{% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

    {% comment %} <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script> {% endcomment %}
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> {% endcomment %}

    {% comment %} <link rel="stylesheet" href="{% static 'dropzone.css' %}" />
    <script src="{% static 'dropzone.js' %}" defer></script> {% endcomment %}

    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />

    {% comment %}Custom css{% endcomment %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />

    <title>
      Report app |{% block title %}

      {% endblock %}
    </title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container mt-3 mb-3">
      {% block content %}

      {% endblock %}
    </div>

    {% comment %} <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script> {% endcomment %}
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> {% endcomment %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

src/templates/navbar.html
{% load static %}
{% url 'sales:home' as path_to_home %}
{% url 'sales:list' as path_to_sales %}
{% url 'reports:form-file' as path_to_form_file %}
{% url 'reports:main' as path_to_reports %}
{% url 'profiles:my' as path_to_my_profile %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href=""><img src="{% static 'logo.png' %}" class="logo-sm" alt="logo" /></a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_home %}active {% endif %}" href="{{path_to_home}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_sales %}active {% endif %}" href="{{path_to_sales}}">Sales</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_form_file %}active{% endif %}" href="{{path_to_form_file}}">Add from file</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_reports %}active{% endif %}" href="{{path_to_reports}}">Reports</a>
        </li>
      </ul>
    </div>
    {% if request.user.is_authenticated %}
   
    <div class="nav-item dropdown">
        <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{request.user.Profile.avatar.url}}" class="avatar-sm" alt="">&nbsp;{{request.user}}
        </div>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item {% if request.path == path_to_my_profile %}active{% endif %}" href="{{path_to_my_profile}}">Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </div> 
    {% endif %}
  </div>
</nav>



 